global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:3000

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: 
         - 'localhost:9100'
         - '191.16.20.10:9100'
         - '191.16.20.20:9100'
         - '191.16.20.30:9100'
         - '191.16.20.40:9100'
         - '191.16.20.50:9100'
         - '191.16.20.60:9100'
         - '191.16.20.70:9100'
  
  - job_name: 'mongo_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: 
         - '191.16.20.10:9216'
         - '191.16.20.20:9216'
         - '191.16.20.30:9216'
         - '191.16.20.40:9216'
         - '191.16.20.50:9216'
         - '191.16.20.60:9216'
         - '191.16.20.70:9216'

