c = new Mongo();
db = c.getDB("cinema");

var filmes = db.filmes.initializeUnorderedBulkOp();

filmes.insert({"titulo":"Asas", "ano":"1929", "diretor":["William A. Wellman"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Melodia na Broadway", "ano":"1930", "diretor":["Harry Beaumont"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Nada de Novo no Front", "ano":"1930", "diretor":["Lewis Milestone"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Cimarron", "ano":"1931", "diretor":["Wesley Ruggles"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Grande Hotel", "ano":"1932", "diretor":["Edmund Goulding"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Cavalgada", "ano":"1934", "diretor":["Frank Lloyd"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Aconteceu Naquela Noite", "ano":"1935", "diretor":["Frank Capra"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"O Grande Motim", "ano":"1936", "diretor":["Frank Lloyd"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Interestelar", "ano":"2014", "diretor":["Christopher Nolan"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Transformers: The Last Knight", "ano":"2017", "diretor":["Michael Bay"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Os Mercenários", "ano":"2010", "diretor":["Sylvester Stallone"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Kill Bill", "ano":"2003", "diretor":["Quentin Tarantino"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Planeta Terror", "ano":"2007", "diretor":["Robert Rodriguez"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Na Natureza Selvagem", "ano":"2008", "diretor":["Sean Penn"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Sobre Meninos e Lobos", "ano":"2003", "diretor":["Clint Eastwood"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Batman: O Cavaleiro das Trevas", "ano":"2008", "diretor":["Christopher Nolan"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Batman vs Superman: A Origem da Justiça", "ano":"2016", "diretor":["Zack Snyder"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Alice no País das Maravilhas", "ano":"2010", "diretor":["Tim Burton"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Harry Potter e o Cálice de Fogo", "ano":"2005", "diretor":["J.K. Rowling"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"A Lista de Schindler", "ano":"1993", "diretor":["Steven Spielberg"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Harry Potter e as Relíquias da Morte:Parte 1", "ano":"2010", "diretor":["J.K. Rowling"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Harry Potter e a Pedra Filosofal", "ano":"2001", "diretor":["J.K. Rowling"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Indiana Jones e a Última Cruzada", "ano":"1989", "diretor":["Steven Spielberg"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Harry Potter e o Enigma do Príncipe", "ano":"2009", "diretor":["J.K. Rowling"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Band of Brothers", "ano":"2001", "diretor":["Steven Spielberg"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Harry Potter e a Ordem da Fênix", "ano":"2007", "diretor":["J.K. Rowling"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Monty Python em Busca do Cálice Sagrado", "ano":"1975", "diretor":["Terry Gilliam","Terry Jones"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"A Vida de Brian", "ano":"1980", "diretor":["Terry Jones"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Ziegfeld: O Criador de Estrelas", "ano":"1937", "diretor":["Robert Z. Leonard"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Émile Zola", "ano":"1938", "diretor":["William Dieterle"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Do Mundo Nada Se Leva", "ano":"1939", "diretor":["Frank Capra"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"E o Vento Levou", "ano":"1940", "diretor":["Victor Fleming", "George Cukor", "Sam Wood"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Rebecca: A Mulher Inesquecível", "ano":"1941", "diretor":["Ben Wheatley "],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Como Era Verde o Meu Vale", "ano":"1942", "diretor":["John Ford"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Rosa da Esperança", "ano":"1943", "diretor":["William Wyler"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Casablanca", "ano":"1943", "diretor":["Michael Curtiz"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"A Volta ao Mundo em 80 Dias", "ano":"1956", "diretor":["Michael Anderson"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Ben-Hur", "ano":"1956", "diretor":["William Wyler"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Pantera Negra", "ano":"2018", "diretor":["Ryan Coogler"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Green Book", "ano":"2018", "diretor":["Peter Farrelly"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Três Anúncios Para um Crime", "ano":"2017", "diretor":["Martin McDonagh"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Dunkirk", "ano":"2017", "diretor":["Christopher Nolan"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"O Destino de uma Nação", "ano":"2017", "diretor":["Joe Wright"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Mad Max: Estrada da Fúria", "ano":"2015", "diretor":["George Miller"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Spotlight: Segredos Revelados", "ano":"2015", "diretor":["Tom McCarthy"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"A Teoria de Tudo", "ano":"2014", "diretor":["James Marsh"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"O Jogo da Imitação", "ano":"2014", "diretor":["Morten Tyldum"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"O Lobo de Wall Street", "ano":"2013", "diretor":["Martin Scorsese"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"12 Anos de Escravidão", "ano":"2013", "diretor":["Steve McQueen"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Django Livre", "ano":"2012", "diretor":["Quentin Tarantino"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"O Homem que Mudou o Jogo", "ano":"2011", "diretor":["Bennett Miller"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"A Origem", "ano":"2010", "diretor":["Christopher Nolan"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"O Discurso do Rei", "ano":"2010", "diretor":["Tom Hooper"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Avatar", "ano":"2009", "diretor":["James Cameron"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Guerra ao Terror", "ano":"2008", "diretor":["Kathryn Bigelow"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"O Curioso Caso de Benjamin Button", "ano":"2008", "diretor":["David Fincher"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Quem Quer Ser Um Milionário?", "ano":"", "diretor":["2008"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Pequena Miss Sunshine", "ano":"2006", "diretor":["Jonathan Dayton", "Valerie Faris"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"O Aviador", "ano":"2004", "diretor":["Martin Scorsese"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Gangues de Nova York", "ano":"2002", "diretor":["Martin Scorsese"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Moulin Rouge: Amor em Vermelho", "ano":"2001", "diretor":["Baz Luhrmann"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Bohemian Rhapsody", "ano":"2018", "diretor":["Bryan Singer"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Nasce Uma Estrela", "ano":"2018", "diretor":["Bradley Cooper", "Will Fetters", "Eric Roth"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"1917", "ano":"2019", "diretor":["Sam Mendes"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"O Irlandês", "ano":"2019", "diretor":["Martin Scorsese"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Era Uma Vez Em Hollywood", "ano":"2019", "diretor":["Quentin Tarantino"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Duna", "ano":"2021", "diretor":["Denis Villeneuve"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"O Senhor dos Aneis: As Duas Torres", "ano":"2002", "diretor":["Peter Jackson"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"O Senhor dos Aneis: O Retorno do Rei", "ano":"2003", "diretor":["Peter Jackson"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"O Senhor dos Aneis: a sociedade do anel", "ano":"2001", "diretor":["Peter Jackson"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Cães de Aluguel", "ano":"1993", "diretor":["Quentin Tarantino"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});
filmes.insert({"titulo":"Psicopata Americano", "ano":"2000", "diretor":["Mary Harron"],"avaliacao":{"bom":0,"medio":0,"ruim":0}});


filmes.execute();
